routes/web.php
<?php

use App\Http\Controllers\admin\ChurchController;
use App\Http\Controllers\admin\ChurchRequestController;
use App\Http\Controllers\admin\ChurchSinodeController;
use App\Http\Controllers\admin\UserController;
use App\Http\Controllers\admin\UserRoleController;
use App\Http\Controllers\admin\VersionController;
use App\Http\Controllers\AuthController;
use App\Http\Livewire\BibleListManagement;
use App\Http\Livewire\BibleManagement;
use App\Http\Livewire\ChurchDashboard;
use App\Http\Livewire\ChurchManagement;
use App\Http\Livewire\ChurchRequestManagement;
use App\Http\Livewire\ChurchSinodeManagement;
use App\Http\Livewire\Dashboard;
use App\Http\Livewire\UserDashboard;
use App\Http\Livewire\UserManagement;
use App\Http\Livewire\UserRoleManagement;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('home');

Route::view('login', 'web/login')->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('test', function () {
    Storage::disk('google')->put('test.txt', 'Hello World');
});

Route::prefix('backoffice')->middleware('loggedin:1,2')->group(function () {
    Route::get('dashboard', Dashboard::class)->name('dashboard');
    Route::middleware('loggedin:1')->resource('version', VersionController::class)->names('version');

    Route::prefix('role')->middleware('loggedin:1')->group(function () {
        Route::resource('data', UserRoleController::class)->names('userrole');
        Route::post('restore', [UserRoleController::class, 'restore'])->name('userrole.restore');
        Route::post('delete', [UserRoleController::class, 'delete'])->name('userrole.delete');
    });

    Route::prefix('user')->middleware('loggedin:1')->group(function () {
        Route::get('dashboard', [UserController::class, 'dashboard'])->name('userdashboard');

        Route::resource('data', UserController::class)->names('userdata');
        Route::post('verify', [UserController::class, 'verify'])->name('userdata.verify');
        Route::post('reset', [UserController::class, 'reset'])->name('userdata.reset');
        Route::post('restore', [UserController::class, 'restore'])->name('userdata.restore');
    });


    Route::prefix('sinode')->middleware('loggedin:1,2')->group(function () {
        Route::resource('data', ChurchSinodeController::class)->names('churchsinode');
        Route::post('restore', [ChurchSinodeController::class, 'restore'])->name('churchsinode.restore');
    });

    Route::prefix('church')->middleware('loggedin:1,2')->group(function () {
        Route::get('dashboard', [ChurchController::class, 'dashboard'])->name('churchdashboard');

        Route::resource('data', ChurchController::class)->names('churchdata');
        Route::post('restore', [ChurchController::class, 'restore'])->name('churchdata.restore');
        Route::post('delete', [ChurchController::class, 'delete'])->name('churchdata.delete');

        Route::resource('request', ChurchRequestController::class)->names('churchrequest');
    });

    Route::prefix('bible')->middleware('loggedin:1')->group(function () {
        Route::get('data', BibleManagement::class)->name('bibledata');
    });
});

app/Http/Controllers/admin/VersionController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\AppVersion;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class VersionController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->search;
        $data = AppVersion::with('creator')->when($search, function ($query) use ($search) {
            return $query->where('version', 'like', '%' . $search . '%')
                ->orWhere('created_by', 'like', '%' . $search . '%');
        })->orderBy('date', 'desc')
            ->paginate(20);

        return view('admin.version.index')
            ->with('data', $data)
            ->with('title', 'App Version');
    }

    public function create()
    {
        return view('admin.version.create')
            ->with('title', 'App Version');
    }

    public function store(Request $request)
    {
        $data = AppVersion::create([
            'version' => $request->version,
            'desc' => $request->desc,
            'platform' => $request->platform,
            'date' => $request->date,
            'created_by' => Auth::id()
        ]);

        return redirect()->route('version.index')->withSuccess('Version Created Successfully!');
    }

    public function edit($id)
    {
        $data = AppVersion::find($id);

        return view('admin.version.edit')
            ->with('data', $data)
            ->with('title', 'App Version');
    }

    public function update(Request $request, $id)
    {
        $data = AppVersion::where('id', $id)
            ->update([
                'version' => $request->version,
                'desc' => $request->desc,
                'platform' => $request->platform,
                'date' => $request->date,
                'created_by' => Auth::id()
            ]);

        return redirect()->route('version.index')->withSuccess('Version Updated Successfully!');
    }

    public function restore(Request $request)
    {
        $data = AppVersion::withTrashed()->where('id', $request->id)->restore();

        return redirect()->route('version.index')->withSuccess('Version Restored Successfully!');
    }

    public function destroy($id)
    {
        $data = AppVersion::where('id', $id)->delete();

        return redirect()->route('version.index')->withSuccess('Version Deleted Successfully!');
    }
}

app/Http/Controllers/api/VersionController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Models\AppVersion;
use App\Models\Church;
use Illuminate\Http\Request;

/**
 * @group App Version Management
 *
 * APIs for checking application and data version
 * @authenticated
 */
class VersionController extends Controller
{
    /**
     * Get Latest App Version Info
     *
     * Get Latest App Version Info, on success you'll get a 200 OK response.
     * Return 422 when parameter is not filled.
     *
     * @bodyParam platform int required Platform to be checked (0: Website, 1: Mobile). Example: 1
     *
     * @responseField success The status of this API request.
     * @responseField result Description of this API request.
     * @responseField data Latest Version data.
     */
    public function app(Request $request)
    {
        if (!$request->filled('platform')) {
            return response()->json(['success' => false, 'result' => 'Missing Parameter'], 422);
        }

        $data = AppVersion::where('platform', $request->platform)->latest()->first();

        return response()->json(['success' => true, 'result' => 'Successfully Latest Version Data', 'data' => $data], 200);
    }

    /**
     * Get Latest Church Timestamp
     *
     * Get Latest Church Timestamp, on success you'll get a 200 OK response.
     *
     * @bodyParam date date required Datetime last time the app sync with the cloud data (yyyy-mm-dd hh:mm:ss). Example: 2021-10-13 11:00:00
     *
     * @responseField success The status of this API request.
     * @responseField result Description of this API request.
     * @responseField data All Church that updated more than given date.
     */
    public function church(Request $request)
    {
        $data = Church::whereDate('updated_at', '>', $request->date)->get();

        return response()->json(['success' => true, 'result' => 'Successfully Latest Church Data', 'data' => $data], 200);
    }
}

resources/views/admin/version/create.blade.php
@extends('admin.app')

@section('content')
<div>
    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-6">
                                    <a href="{{ route('version.index') }}" class="btn btn-dark"><i class="fas fa-chevron-left pr-1"></i> Back</a>
                                </div>
                            </div>
                        </div>

                        <form method="post" action="{{route('version.store')}}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="version">Version Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" name="version" id="version" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="platform">Platform</label>
                                    <div class="col-sm-10">
                                        <select name="platform" class="form-control" required>
                                            <option value="" selected="selected">-- Select Platform --</option>
                                            <option value="0">Website</option>
                                            <option value="1">Mobile App</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="date">Released Date</label>
                                    <div class="col-sm-10">
                                        <input type="date" class="form-control" name="date" required="required"
                                        data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="date">Description</label>
                                    <div class="col-sm-10">
                                        <textarea class="form-control" name="desc" rows="7"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/version/edit.blade.php
@extends('admin.app')

@section('content')
<div>
    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-6">
                                    <a href="{{ route('version.index') }}" class="btn btn-dark"><i class="fas fa-chevron-left pr-1"></i> Back</a>
                                </div>
                            </div>
                        </div>

                        <form method="post" action="{{route('version.update', $data->id)}}">
                            @csrf
                            @method('put')
                            <div class="card-body">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="version">Version Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" name="version" id="version" class="form-control" value="{{$data->version}}" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="platform">Platform</label>
                                    <div class="col-sm-10">
                                        <select name="platform" class="form-control" required>
                                            <option value="" selected="selected">-- Select Platform --</option>
                                            <option value="0" @if($data->platform==0) selected @endif>Website</option>
                                            <option value="1" @if($data->platform==1) selected @endif>Mobile App</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="date">Released Date</label>
                                    <div class="col-sm-10">
                                        <input type="date" class="form-control" name="date" required="required" value="{{$data->date}}"
                                        data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label" for="date">Description</label>
                                    <div class="col-sm-10">
                                        <textarea class="form-control" name="desc" rows="7">{{$data->desc}}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-right">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/version/index.blade.php
@extends('admin.app')

@section('content')
<div>
    <div class="content-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-6">
                                    <a href=" {{ route('version.create') }}" class="btn btn-dark"><i class="fas fa-plus pr-1"></i> Add New</a>
                                </div>
                                <div class="col-6">
                                    <form method="GET">
                                        <div class="input-group">
                                            <input name="search" type="search" class="form-control form-control-lg" placeholder="Search Something">
                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-lg btn-default">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover m-0">
                                    <thead class="text-center">
                                        <tr>
                                            <th width="5%">#</th>
                                            <th class="text-left">VERSION</th>
                                            <th class="text-left">TYPE</th>
                                            <th class="text-left">DATE</th>
                                            <th class="text-left">DESCRIPTION</th>
                                            <th class="text-left">CREATOR</th>
                                            <th width="10%"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($data as $d)
                                        <tr>
                                            <td class="text-center">{{ 10*($data->currentPage()-1)+$loop->iteration}}</td>
                                            <td>{{ $d->version }}</td>
                                            <td>{{ $d->platform == 1 ? 'Mobile App' : 'Website' }}</td>
                                            <td>{{ $d->created_at }}</td>
                                            <td style="white-space: pre-line;">{{ $d->desc }}</td>
                                            <td>{{ $d->creator->name }}</td>
                                            <td style="text-align: center;">
                                                <form method="post" id="{{'delete'.$d->id}}" action="{{ route('version.destroy', $d->id) }}" onsubmit="return confirm('Are you sure to delete?');">
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    @csrf
                                                </form>

                                                <a href="{{ route('version.edit', $d->id) }}" class="btn btn-sm btn-info" style="width:auto; margin: 2px"><i class="fas fa-edit"></i></a>
                                                <button form="{{'delete'.$d->id}}" type="submit" class="btn btn-sm btn-danger" style="width:auto; margin: 2px">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="7">No Data Available</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer">
                            @include('admin.layout.tablecountinfo')
                            <div class="text-xs" style="float: right">
                            @if($data->hasPages())
                                {{ $data->links() }}
                            @endif
                            </div>
                        </div>
                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
@endsection