routes/web.php
<?php

use App\Http\Controllers\admin\ChurchController;
use App\Http\Controllers\admin\ChurchRequestController;
use App\Http\Controllers\admin\ChurchSinodeController;
use App\Http\Controllers\admin\UserController;
use App\Http\Controllers\admin\UserRoleController;
use App\Http\Controllers\admin\VersionController;
use App\Http\Controllers\AuthController;
use App\Http\Livewire\BibleListManagement;
use App\Http\Livewire\BibleManagement;
use App\Http\Livewire\ChurchDashboard;
use App\Http\Livewire\ChurchManagement;
use App\Http\Livewire\ChurchRequestManagement;
use App\Http\Livewire\ChurchSinodeManagement;
use App\Http\Livewire\Dashboard;
use App\Http\Livewire\UserDashboard;
use App\Http\Livewire\UserManagement;
use App\Http\Livewire\UserRoleManagement;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('home');

Route::view('login', 'web/login')->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('test', function () {
    Storage::disk('google')->put('test.txt', 'Hello World');
});

Route::prefix('backoffice')->middleware('loggedin:1,2')->group(function () {
    Route::get('dashboard', Dashboard::class)->name('dashboard');
    Route::middleware('loggedin:1')->resource('version', VersionController::class)->names('version');

    Route::prefix('role')->middleware('loggedin:1')->group(function () {
        Route::resource('data', UserRoleController::class)->names('userrole');
        Route::post('restore', [UserRoleController::class, 'restore'])->name('userrole.restore');
        Route::post('delete', [UserRoleController::class, 'delete'])->name('userrole.delete');
    });

    Route::prefix('user')->middleware('loggedin:1')->group(function () {
        Route::get('dashboard', [UserController::class, 'dashboard'])->name('userdashboard');

        Route::resource('data', UserController::class)->names('userdata');
        Route::post('verify', [UserController::class, 'verify'])->name('userdata.verify');
        Route::post('reset', [UserController::class, 'reset'])->name('userdata.reset');
        Route::post('restore', [UserController::class, 'restore'])->name('userdata.restore');
    });


    Route::prefix('sinode')->middleware('loggedin:1,2')->group(function () {
        Route::resource('data', ChurchSinodeController::class)->names('churchsinode');
        Route::post('restore', [ChurchSinodeController::class, 'restore'])->name('churchsinode.restore');
    });

    Route::prefix('church')->middleware('loggedin:1,2')->group(function () {
        Route::get('dashboard', [ChurchController::class, 'dashboard'])->name('churchdashboard');

        Route::resource('data', ChurchController::class)->names('churchdata');
        Route::post('restore', [ChurchController::class, 'restore'])->name('churchdata.restore');
        Route::post('delete', [ChurchController::class, 'delete'])->name('churchdata.delete');

        Route::resource('request', ChurchRequestController::class)->names('churchrequest');
    });

    Route::prefix('bible')->middleware('loggedin:1')->group(function () {
        Route::get('data', BibleManagement::class)->name('bibledata');
    });
});

resources/views/admin/layout/css.blade.php
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('admin/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{{ asset('admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('admin/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('admin/plugins/jqvmap/jqvmap.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/adminlte.min.css') }}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset('admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('admin/plugins/daterangepicker/daterangepicker.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('admin/plugins/summernote/summernote-bs4.min.css') }}">

@yield('style')

resources/views/admin/layout/footer.blade.php
<footer class="main-footer">
    <strong><a href="https://ezlife.id">EZ-Life Developer</a> &copy; 2017 - {{date('Y')}}</strong>
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0.0
    </div>
</footer>

resources/views/admin/layout/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="shortcut icon" type="image/png" href="{{ asset('favicon.ico') }}">

<meta name="description" content="EZ-Life adalah pengembang aplikasi website, android, ios, maupun desktop yang mengutamakan kenyamanan client, ketepatan waktu, dan hasil yang maksimal dan optimal">
<meta name="author" content="EZ-Life Developer">
<meta property="og:description" content="EZ-Life adalah pengembang aplikasi website, android, ios, maupun desktop" />
<meta property="og:url" content="{{ env("APP_URL") }}" />
<meta property="og:image" content="{{ asset('logo.jpg') }}" />
<meta property="og:title" content="{{ env("APP_NAME") }}" />
<meta property="og:type" content="portfolio" />
<meta property="og:locale:alternate" content="in_ID" />

<meta name="twitter:card" content="summary" />
{{-- <meta name="twitter:site" content="@ezlifedeveloper" />
<meta name="twitter:creator" content="@ezlifedeveloper" /> --}}

resources/views/admin/layout/js.blade.php
<!-- jQuery -->
<script src="{{ asset('admin/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('admin/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('admin/plugins/select2/js/select2.full.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('admin/plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('admin/plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
<script src="{{ asset('admin/plugins/jqvmap/jquery.vmap.min.js') }}"></script>
<script src="{{ asset('admin/plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('admin/plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('admin/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('admin/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('admin/dist/js/pages/dashboard.js') }}"></script>

<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2();

    });

    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                var link = document.getElementById('imgpreview');
                link.style.display = 'block';
                $('#imgpreview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@yield('script')

resources/views/admin/layout/nav.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <p class="nav-link" style="margin: 0px">{{ $title }}</p>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
            <form class="form-inline">
                <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                    </button>
                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                    </button>
                </div>
                </div>
            </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-comments"></i>
            <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                            Brad Diesel
                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">Call me whenever you can...</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                </div>
                </div>
                <!-- Message End -->
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                            John Pierce
                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">I got your message bro</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                </div>
                </div>
                <!-- Message End -->
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                <div class="media-body">
                    <h3 class="dropdown-item-title">
                            Nora Silvester
                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                    </h3>
                    <p class="text-sm">The subject goes here</p>
                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                </div>
                </div>
                <!-- Message End -->
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <i class="fas fa-th-large"></i>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <img src="{{ Auth::user()->photo ?? asset('logo.jpg') }}" class="img-circle" width="24px" height="24px" alt="User Image">
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">{{ Auth::user()->name }}</span>
                <div class="dropdown-divider"></div>
                <span class="dropdown-item dropdown-header">{{ Auth::user()->point.' pts' }}</span>
                <div class="dropdown-divider"></div>
                <a href="{{route('logout')}}" class="dropdown-item dropdown-footer">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/admin/layout/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('home') }}" class="brand-link">
        <img src="{{ asset('logo.jpg') }}" alt="{{ env('APP_NAME') }} Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">{{ env('APP_NAME') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- SidebarSearch Form -->
        <div class="form-inline mt-2">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @if(in_array(Auth::user()->role_id, [1]))
                <li class="nav-header">Dashboard</li>
                <li class="nav-item">
                    <a href="{{ route('dashboard') }}" class="nav-link @if(in_array($title, ['Dashboard'])) active @endif">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                            {{-- <span class="right badge badge-danger">New</span> --}}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('version.index') }}" class="nav-link @if(in_array($title, ['App Version'])) active @endif">
                        <i class="nav-icon fa fa-history"></i>
                        <p>
                            App Version
                            {{-- <span class="right badge badge-danger">New</span> --}}
                        </p>
                    </a>
                </li>
                @endif
                @if(in_array(Auth::user()->role_id, [1, 2]))
                <li class="nav-header">CHURCH</li>
                <li class="nav-item">
                        <a href="{{ route('churchdashboard') }}" class="nav-link @if(in_array($title, ['Church Dashboard'])) active @endif">
                        <i class="fas fa-tachometer-alt nav-icon"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('churchsinode.index') }}" class="nav-link @if(in_array($title, ['Church Sinode'])) active @endif">
                        <i class="fas fa-database nav-icon"></i>
                        <p>Sinode</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('churchdata.index') }}" class="nav-link @if(in_array($title, ['Church Data'])) active @endif">
                        <i class="fas fa-church nav-icon"></i>
                        <p>Data</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('churchrequest.index') }}" class="nav-link @if(in_array($title, ['Church Request'])) active @endif">
                        <i class="fas fa-folder-open nav-icon"></i>
                        <p>Request</p>
                    </a>
                </li>
                @endif
                @if(Auth::user()->role_id == 1)
                <li class="nav-header">BIBLE</li>
                <li class="nav-item">
                    <a href="{{ route('bibledata') }}" class="nav-link @if(in_array($title, ['Bible Data'])) active @endif">
                        <i class="fas fa-book nav-icon"></i>
                        <p>Data</p>
                    </a>
                </li>
                @endif
                @if(Auth::user()->role_id == 1)
                <li class="nav-header">USER</li>
                <li class="nav-item">
                        <a href="{{ route('userdashboard') }}" class="nav-link @if(in_array($title, ['User Dashboard'])) active @endif">
                        <i class="fas fa-tachometer-alt nav-icon"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('userrole.index') }}" class="nav-link @if(in_array($title, ['User Role'])) active @endif">
                        <i class="fas fa-database nav-icon"></i>
                        <p>Role</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('userdata.index') }}" class="nav-link @if(in_array($title, ['User Data'])) active @endif">
                        <i class="fas fa-user nav-icon"></i>
                        <p>Data</p>
                    </a>
                </li>
                @endif
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/admin/layout/sidebox.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/admin/layout/tablecountinfo.blade.php
Showing {{($data->currentPage()-1)* $data->perPage()+($data->total() ? 1:0)}} to {{($data->currentPage()-1)*$data->perPage()+count($data)}}  of  {{$data->total()}}  Results